# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b3d47928378841de29cf794be3038c6d8d049046ca477ddf86d1820c40e37f3e8988acc70e08da469072e80e9a2ae5285193e297f44d9e3758b6a0a6e10550b

test:
  secret_key_base: a3fc5ed991c6d9d929eedbca272c22198d13aa24f264ee1360958ec765318b9d35313f74b698520518942802e212c92848326d9658c8084d82e6a146ae82b6c1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
